# -*- coding: utf-8 -*-
"""codechef programs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCAWXS2L3feWNU2gM5IpU5jX2DFq7aym
"""

#1 RAINBOWA
T = int(input())
for _ in range(T):
    n = int(input())
    a = list(map(int, input().split()))
    if a != a[::-1]:
        print("no")
        continue
    if set(a) != {1, 2, 3, 4, 5, 6, 7}:
        print("no")
        continue
    elements = []
    for x in a:
        if not elements or elements[-1] != x:
            elements.append(x)

    if elements == [1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1]:
        print("yes")
    else:
        print("no")

#2 NOTINCOM
t=int(input())
for i in range(t):
    n,m=map(int,input().split())
    A=set(map(int,input().split()))
    B=set(map(int,input().split()))
    print(len(A&B))

#3 FLOW017
t = int(input())

for i in range(t):

    a, b, c = map(int, input().split())

    if (a > b and a < c) or (a > c and a < b):
        print(a)

    elif (b > a and b < c) or (b > c and b < a):
        print(b)

    else:
        print(c)

#4 FLOW009
t = int(input())

for i in range(t):

    quantity, price = map(int, input().split())

    total = quantity * price

    if quantity > 1000:
        total = total - (0.10 * total)

    print("{:.6f}".format(total))

#5 FLOW014
t = int(input())

for i in range(t):
    hardness,carbon_content,tensile_strength=input().split()

    hardness = int(hardness)
    carbon_content = float(carbon_content)
    tensile_strength = int(tensile_strength)

    if hardness > 50 and carbon_content < 0.7 and tensile_strength > 5600:
        print(10)

    elif hardness > 50 and carbon_content < 0.7:
        print(9)

    elif carbon_content < 0.7 and tensile_strength > 5600:
        print(8)

    elif hardness > 50 and tensile_strength > 5600:
        print(7)

    elif hardness > 50 or carbon_content < 0.7 or tensile_strength > 5600:
        print(6)

    else:
        print(5)

#6 FLOW013
t=int(input())
for i in range (t):
    a,b,c=map(int,input().split())
    s=a+b+c
    if(s==180):
        print("YES")
    else:
         print("NO")

#7 FLOW011
t = int(input())

for i in range(t):
    salary = int(input())

    if salary < 1500:
        HRA = 10 * salary/100
        DA = 90 * salary/100
    else:
        HRA = 500
        DA = 98 * salary/100

    GrossSalary = salary + HRA + DA

    print(GrossSalary)

#8 START01
n=int(input())
print(n)

#9 TABLET

t = int(input())

for _ in range(t):
    n, b = map(int, input().split())

    area = 0

    for _ in range(n):
        w, h, p = map(int, input().split())

        if p <= b:
            if w * h > area:
                area = w * h

    if area == 0:
        print("no tablet")
    else:
        print(area)

#10. JOHNY

t = int(input())

for _ in range(t):
    n = int(input())
    a = list(map(int, input().split()))
    k = int(input())

    song = a[k - 1]

    a.sort()

    for i in range(n):
        if a[i] == song:
            print(i + 1)
            break

#11. LECANDY

t=int(input())
for _ in range(t):
    n,c=list(map(int,input().split()))
    num=list(map(int,input().split()))
    rem=c
    count=0
    for i in range(n):
        if(rem<num[i]):
            print("No")
            break
        else:
            rem-=num[i]
            count+=1
            if(count==len(num)):
                print("Yes")
                break
            else:
                pass

#12. HEADBOB

t=int(input())
for _ in range(t):
    num=int(input())
    n=input()
    if(n.count("N")==num):
        print("NOT SURE")
    else:
        if "I" in n:
            print("INDIAN")
        elif "Y" in n:
            print("NOT INDIAN")

#13. LAPIN
t=int(input())
def freq(s1, s2):
    for c in set(s2):
        if s2.count(c)>s1.count(c):
            return False
    return True
for _ in range(t):
    n=input()
    if(len(n)%2==0):
        s1=n[0:int(len(n)/2)]
        s2=n[int(len(n)/2):]
        if(s1==s2[::-1] or s1==s2 or freq(s1,s2)):
            print("YES")
        else:
            print("NO")
    else:
        i=int(len(n)/2)
        s1=n[0:i]
        s2=n[i+1:]
        if(s1==s2[::-1] or s1==s2 or freq(s1,s2)):
            print("YES")
        else:
            print("NO")

#14. STONES

t=int(input())
for _ in range(t):
    count=0
    j=input()
    s=input()
    for i in s:
        if i in j:
            count+=1
    print(count)

#15  VOWELTB
n=input()
n=n.lower()
vowels=['a','e','i','o','u']
if n in vowels:
    print("Vowel")
else:
    print("Consonant")

#16 CHN15A
n=int(input())
for _ in range(n):
    n,k=list(map(int,input().split()))
    num=list(map(int,input().split()))
    count=0
    for i in num:
        summ=i+k
        if(summ%7==0):
            count+=1
    print(count)

#17 CHEFPAROLE
n=int(input())
if(n>=7):
    print("YES")
else:
    print("NO")

#18 LMP1
a,b=list(map(int, input().split()))
if(a>=b):
    print("YES")
else:
    print("NO")

#19 TRICHECK

# cook your dish here
a,b,c=list(map(int, input().split()))
if (a+b)>c and (b+c)>a and (c+a)>b:
    print("Yes")
else:
    print("No")

#20 TEST

while True:
    n = int(input())
    if n == 42:
        break
    print(n)

#21  FLOW018
t=int(input())
for _ in range(t):
    n=int(input())
    fact=1
    for i in range(1,n+1):
        fact*=i
    print(fact)

#22 FCTRL2
t=int(input())
for _ in range(t):
    n=int(input())
    fact=1
    for i in range(1,n+1):
        fact*=i
    print(fact)

#23 LUCKYFR
t=int(input())
for _ in range(t):
    n=input()
    count=0
    for i in n:
        if i=='4':
            count+=1
    print(count)

#24. PALL01
t=int(input())
for _ in range(t):
    n=input()
    if(n[::-1]==n):
        print("wins")
    else:
        print("loses")

#25 FLOW007

# cook your dish here
t=int(input())
for i in range(t):
  n=input()
  rev=n[::-1]
  print(int(rev))

#26  AMR15A

# cook your dish here
n=int(input())
ready=0
notready=0
num=list(map(int,input().split()))
for i in num:
    if(i%2==0):
        ready+=1
    else:
        notready+=1
if n==1:
    print("READY FOR BATTLE")
elif(ready>notready):
    print("READY FOR BATTLE")
else:
    print("NOT READY")

#27 FSQRT
t=int(input())
for _ in range(t):
    n=int(input())
    print(int(n**0.5))

#28  INTEST

(n, k) = map(int, input().split())

ans = 0

for i in range(n):
	x = int(input())
	if x % k == 0:
		ans += 1

print(ans)





