# -*- coding: utf-8 -*-
"""python_technical_class_prgs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wBY3ssTtCQttjhANIO0yZPBRQwtoTq-x
"""

#1 factorial program
n=5
fact=1
for i in range (1,n+1):
 fact*=i
print(fact)

#2 palindrome
text="MALAYALAM"
if text == text[::-1]:
  print("palindrome")
else:
     print("no")

#3 to print greater element
a=int(input())
b=int(input())
if(a<b):
  print("a is greater")
else:
    print("b")

#4 Type Conversion (Type Casting)
a="8"
print(type(a))
b=int(a)
print(type(b))



#5 convert Fahrenheit to Celsius
f=int(int(input()))
c=f-32*5/9
print(c)

#6 to swap numbers
a=10
b=20
a,b=b,a
print(a,b)

#7 fibonacci series
a = 0
b = 1

for i in range(10):
    print(a, end=" ")

    c = a + b
    a = b
    b = c

#8 to print average
a=80
b=50
c=90
d=a+b+c/3
print("average:",d)

#9 prints prime numbers from 1 to 50.
for num in range(1,51):
  for i in range(2,num+1):
    if(num%i==0):
      break
  if(num==i):
    print(num)

#10 print pattern
for i in range(1,6):
    print("*"*i)

#11 to print no.of vowels

n=input()
l=['a','e','i','o','u']
count=0
for ch in n:
  if ch.lower()in l:
    print("vowels present:",ch)
    count+=1
print("no of vowels:",count)

#12 to print smallest and largest number
num=list(map (int,input("enter the numbers").split()))
largest=max(num)
smallest=min(num)
print("largest",largest)
print("smallest",smallest)

#13 to find lcm and gcd
a=int(input("enter a number"))
b=int(input("enter b"))
x=a
y=b
while b!=0:
  a,b=b,a%b
gcd=a
lcm=x*y//gcd
print("lcm",lcm)
print("gcd",gcd)

#14 reverse the vowels in srting
s=input()
vowels="aeiouAEIOU"
v=[]
for i in s:
  if i in vowels:
    v.append(i)
  v.reverse()
  result=" "
for i in s:
    if i in vowels:
      result+=v.pop(0)
    else:
        result+=i
print(result)

#15 printing smallest missing number in array
num=[1,2,3,5,8,9,-9]
smallest=1
while smallest in num:
  smallest+=1
print(smallest)

#16 check if the string differ by 1
s1=input()
s2=input()
Count=0
if(len(s1)==len(s2)):
  for i in range(len(s1)):
    if s1[i]!=s2[i]:
      Count+=1
  if Count==1:
      print("yes")
  else:
      print("no")
else:
  print("string not valid unequal")

#17 Longest substring length
s = input("Enter a string: ")

longest = 0

for i in range(len(s)):
    seen = ""

    for j in range(i, len(s)):

        if s[j] not in seen:
            seen += s[j]

            if len(seen) > longest:
                longest = len(seen)

        else:
            break

print("Longest substring length:", longest)

#17. classes and objects

class Student:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def display(self):
    print("Name:",self.name)
    print("age:",self.age)
obj= Student("ABC",3)
obj.display()

#18. inheritance

class father:
  def bike(self):
    print("father has bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj=son()
obj.bike()

#19. pass keyword in inheritance

class father:
  def property(self):
    print("father property")
class son(father):
  pass
obj=son()
obj.property()

#20. Polymorphism (Method overriding)

class animal:
  def sound(self):
    print("animal makes sound")
class dog(animal):
  def sound(sef):
    print("dog barks")
obj=dog()
obj.sound()

#21. abstraction

class bank:
  def __init__(self):
    self.__balance=5000
  def show_balance(self):
    print("balance:",self.__balance)
obj=bank()
obj.show_balance()

#22. Polymorphism (Method overloading)

class Multiply:
  def product(self, a=None, b=None, c=None):
    if a is not None and b is not None and c is not None:
      print("product=",a*b*c)
    elif a is not None and b is not None:
      print("product=",a*b)
    else:
      print("invalid")
obj=Multiply()
obj.product(2,3)
obj.product(2,3,4)



#23. Number and reverse should be prime number
r=int(str(n)[::-1])
def prime(x):
  return x>1 and all (x%i for i in range(2,x))
if prime(n) and prime(r):
    print("Both are prime")
else:
   print("Not prime")

#24. Adam's number
rev=int(str(n)[::-1])
sqr1=n*n
sqr2=rev*rev
rev_sqr1=int(str(sqr1)[::-1])
if rev_sqr1==sqr2:
  print("adam number")
else:
  print("not a adam number")

#25 circular prime
n=input()**


def prime(x):
  if x<2:
    return False
  for i in range(2,x):
    if x%i==0:
     return False
  return True
Flag=True
for i in range(len(n)):
  rotation=n[i:]+n[:i]
  if not prime(int(rotation)):
    Flag=False
if Flag:
  print("circular prime")
else:
  print("nota circular prime")

#26 checking whether it is a palindrome if a character is removed:
s=input()
for i in range(len(s)):
  t=s[:i]+s[i+1:]
  if t==t[::-1]:
    print("palindrome")
    break
else:
    print("not")

#27 printing the missing number
arr=[1,2,3,6,7.-9]
missing=1
while  missing in arr:
  missing +=1
print(missing)

#28 to find duplicate found or not
arr=input().split()
seen=[]
for i in arr:
  if i in seen:
    print("duplicate found")
    break
  seen.append(i)
else:
 print("not found")

#29. Find trendy word

num=list(input().split())
num.sort()
itemdict={}
for n in num:
  itemdict[n]=num.count(n)
values=list(itemdict.values())
keys=list(itemdict.keys())
for i in range(len(values)):
  if(values[i]==max(values)):
    print(keys[i])
    break
print(itemdict)

#30. Transaction approval

b=int(input())
a=int(input())
rem=b-a
if(rem<1000):
  print("Transaction Denied")
else:
  print("Transaction Successful")

#31. Unauthorized users

num1=list(input().split())
num2=list(input().split())
atlist=[]
for i in num2:
  if(i in num1):
    pass
  else:
    atlist.append(int(i))
atlist=set(atlist)
print("Unauthorized users",atlist)

#32. Launch approval

f=int(input())
p=int(input())
if(f>=5000 and p<=1000):
  print("Launch approved")
else:
  print("Launch not approved")

#33. Collision risk

import ast

c1=ast.literal_eval(input())
c2=ast.literal_eval(input())
d=(((c2[0]-c1[0])**2)+((c2[1]-c2[0])**2))**(1/2)
if d<10:
  print('Collision risk')

#34. Password Integrity

import string

password = input()

has_lower = any(c in string.ascii_lowercase for c in password)
has_upper = any(c in string.ascii_uppercase for c in password)
has_digit = any(c in string.digits for c in password)

if has_lower and has_upper and has_digit and len(password) >= 8:
    print("Strong Password")
else:
    print("Weak Password")

#35. Diamond pattern

n=3
for i in range(1,n+1):
  print(" " * (n-i) + "* " * i)
for i in range(n-1,0,-1):
  print(" " * (n-i) + "* " * i)

#36. Pattern (left right-angled triangle)

n=int(input())
for i in range(n):
  print(" " * i + "*" * (n-i))

#37. Triangle pattern

n=6
for i in range(1,n+1):
  print(" " * (n-i) + "* " * i)

#38. Leap year

y=int(input())
if(y%4==0 and y%100!=0 or y%400==0):
  print("Leap year")
else:
  print("Not a leap year")

#39. Armstrong number

n=153
sum=0
s=str(n)
for i in s:
  num=int(i)
  sum+=(num**3)
if(sum==n):
  print("Armstrong number")
else:
  print("Not armstrong number")

#40. Number pattern

n=int(input())
for i in range(1,n):
  for j in range(1,i+1):
    print(j,end=" ")
  print()